<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Redis;

class RedisCity extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Redis::connection('sentinel')->lpush('kota11','{"id":"1101","text":"KABUPATEN SIMEULUE"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1102","text":"KABUPATEN ACEH SINGKIL"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1103","text":"KABUPATEN ACEH SELATAN"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1104","text":"KABUPATEN ACEH TENGGARA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1105","text":"KABUPATEN ACEH TIMUR"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1106","text":"KABUPATEN ACEH TENGAH"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1107","text":"KABUPATEN ACEH BARAT"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1108","text":"KABUPATEN ACEH BESAR"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1109","text":"KABUPATEN PIDIE"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1110","text":"KABUPATEN BIREUEN"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1111","text":"KABUPATEN ACEH UTARA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1112","text":"KABUPATEN ACEH BARAT DAYA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1113","text":"KABUPATEN GAYO LUES"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1114","text":"KABUPATEN ACEH TAMIANG"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1115","text":"KABUPATEN NAGAN RAYA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1116","text":"KABUPATEN ACEH JAYA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1117","text":"KABUPATEN BENER MERIAH"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1118","text":"KABUPATEN PIDIE JAYA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1171","text":"KOTA BANDA ACEH"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1172","text":"KOTA SABANG"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1173","text":"KOTA LANGSA"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1174","text":"KOTA LHOKSEUMAWE"}');
        Redis::connection('sentinel')->lpush('kota11','{"id":"1175","text":"KOTA SUBULUSSALAM"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1201","text":"KABUPATEN NIAS"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1202","text":"KABUPATEN MANDAILING NATAL"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1203","text":"KABUPATEN TAPANULI SELATAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1204","text":"KABUPATEN TAPANULI TENGAH"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1205","text":"KABUPATEN TAPANULI UTARA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1206","text":"KABUPATEN TOBA SAMOSIR"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1207","text":"KABUPATEN LABUHAN BATU"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1208","text":"KABUPATEN ASAHAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1209","text":"KABUPATEN SIMALUNGUN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1210","text":"KABUPATEN DAIRI"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1211","text":"KABUPATEN KARO"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1212","text":"KABUPATEN DELI SERDANG"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1213","text":"KABUPATEN LANGKAT"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1214","text":"KABUPATEN NIAS SELATAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1215","text":"KABUPATEN HUMBANG HASUNDUTAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1216","text":"KABUPATEN PAKPAK BHARAT"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1217","text":"KABUPATEN SAMOSIR"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1218","text":"KABUPATEN SERDANG BEDAGAI"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1219","text":"KABUPATEN BATU BARA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1220","text":"KABUPATEN PADANG LAWAS UTARA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1221","text":"KABUPATEN PADANG LAWAS"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1222","text":"KABUPATEN LABUHAN BATU SELATAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1223","text":"KABUPATEN LABUHAN BATU UTARA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1224","text":"KABUPATEN NIAS UTARA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1225","text":"KABUPATEN NIAS BARAT"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1271","text":"KOTA SIBOLGA"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1272","text":"KOTA TANJUNG BALAI"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1273","text":"KOTA PEMATANG SIANTAR"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1274","text":"KOTA TEBING TINGGI"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1275","text":"KOTA MEDAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1276","text":"KOTA BINJAI"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1277","text":"KOTA PADANGSIDIMPUAN"}');
        Redis::connection('sentinel')->lpush('kota12','{"id":"1278","text":"KOTA GUNUNGSITOLI"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1301","text":"KABUPATEN KEPULAUAN MENTAWAI"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1302","text":"KABUPATEN PESISIR SELATAN"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1303","text":"KABUPATEN SOLOK"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1304","text":"KABUPATEN SIJUNJUNG"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1305","text":"KABUPATEN TANAH DATAR"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1306","text":"KABUPATEN PADANG PARIAMAN"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1307","text":"KABUPATEN AGAM"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1308","text":"KABUPATEN LIMA PULUH KOTA"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1309","text":"KABUPATEN PASAMAN"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1310","text":"KABUPATEN SOLOK SELATAN"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1311","text":"KABUPATEN DHARMASRAYA"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1312","text":"KABUPATEN PASAMAN BARAT"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1371","text":"KOTA PADANG"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1372","text":"KOTA SOLOK"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1373","text":"KOTA SAWAH LUNTO"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1374","text":"KOTA PADANG PANJANG"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1375","text":"KOTA BUKITTINGGI"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1376","text":"KOTA PAYAKUMBUH"}');
        Redis::connection('sentinel')->lpush('kota13','{"id":"1377","text":"KOTA PARIAMAN"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1401","text":"KABUPATEN KUANTAN SINGINGI"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1402","text":"KABUPATEN INDRAGIRI HULU"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1403","text":"KABUPATEN INDRAGIRI HILIR"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1404","text":"KABUPATEN PELALAWAN"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1405","text":"KABUPATEN S I A K"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1406","text":"KABUPATEN KAMPAR"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1407","text":"KABUPATEN ROKAN HULU"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1408","text":"KABUPATEN BENGKALIS"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1409","text":"KABUPATEN ROKAN HILIR"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1410","text":"KABUPATEN KEPULAUAN MERANTI"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1471","text":"KOTA PEKANBARU"}');
        Redis::connection('sentinel')->lpush('kota14','{"id":"1473","text":"KOTA D U M A I"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1501","text":"KABUPATEN KERINCI"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1502","text":"KABUPATEN MERANGIN"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1503","text":"KABUPATEN SAROLANGUN"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1504","text":"KABUPATEN BATANG HARI"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1505","text":"KABUPATEN MUARO JAMBI"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1506","text":"KABUPATEN TANJUNG JABUNG TIMUR"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1507","text":"KABUPATEN TANJUNG JABUNG BARAT"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1508","text":"KABUPATEN TEBO"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1509","text":"KABUPATEN BUNGO"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1571","text":"KOTA JAMBI"}');
        Redis::connection('sentinel')->lpush('kota15','{"id":"1572","text":"KOTA SUNGAI PENUH"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1601","text":"KABUPATEN OGAN KOMERING ULU"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1602","text":"KABUPATEN OGAN KOMERING ILIR"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1603","text":"KABUPATEN MUARA ENIM"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1604","text":"KABUPATEN LAHAT"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1605","text":"KABUPATEN MUSI RAWAS"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1606","text":"KABUPATEN MUSI BANYUASIN"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1607","text":"KABUPATEN BANYU ASIN"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1608","text":"KABUPATEN OGAN KOMERING ULU SELATAN"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1609","text":"KABUPATEN OGAN KOMERING ULU TIMUR"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1610","text":"KABUPATEN OGAN ILIR"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1611","text":"KABUPATEN EMPAT LAWANG"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1612","text":"KABUPATEN PENUKAL ABAB LEMATANG ILIR"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1613","text":"KABUPATEN MUSI RAWAS UTARA"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1671","text":"KOTA PALEMBANG"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1672","text":"KOTA PRABUMULIH"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1673","text":"KOTA PAGAR ALAM"}');
        Redis::connection('sentinel')->lpush('kota16','{"id":"1674","text":"KOTA LUBUKLINGGAU"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1701","text":"KABUPATEN BENGKULU SELATAN"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1702","text":"KABUPATEN REJANG LEBONG"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1703","text":"KABUPATEN BENGKULU UTARA"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1704","text":"KABUPATEN KAUR"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1705","text":"KABUPATEN SELUMA"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1706","text":"KABUPATEN MUKOMUKO"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1707","text":"KABUPATEN LEBONG"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1708","text":"KABUPATEN KEPAHIANG"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1709","text":"KABUPATEN BENGKULU TENGAH"}');
        Redis::connection('sentinel')->lpush('kota17','{"id":"1771","text":"KOTA BENGKULU"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1801","text":"KABUPATEN LAMPUNG BARAT"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1802","text":"KABUPATEN TANGGAMUS"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1803","text":"KABUPATEN LAMPUNG SELATAN"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1804","text":"KABUPATEN LAMPUNG TIMUR"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1805","text":"KABUPATEN LAMPUNG TENGAH"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1806","text":"KABUPATEN LAMPUNG UTARA"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1807","text":"KABUPATEN WAY KANAN"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1808","text":"KABUPATEN TULANGBAWANG"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1809","text":"KABUPATEN PESAWARAN"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1810","text":"KABUPATEN PRINGSEWU"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1811","text":"KABUPATEN MESUJI"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1812","text":"KABUPATEN TULANG BAWANG BARAT"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1813","text":"KABUPATEN PESISIR BARAT"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1871","text":"KOTA BANDAR LAMPUNG"}');
        Redis::connection('sentinel')->lpush('kota18','{"id":"1872","text":"KOTA METRO"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1901","text":"KABUPATEN BANGKA"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1902","text":"KABUPATEN BELITUNG"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1903","text":"KABUPATEN BANGKA BARAT"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1904","text":"KABUPATEN BANGKA TENGAH"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1905","text":"KABUPATEN BANGKA SELATAN"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1906","text":"KABUPATEN BELITUNG TIMUR"}');
        Redis::connection('sentinel')->lpush('kota19','{"id":"1971","text":"KOTA PANGKAL PINANG"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2101","text":"KABUPATEN KARIMUN"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2102","text":"KABUPATEN BINTAN"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2103","text":"KABUPATEN NATUNA"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2104","text":"KABUPATEN LINGGA"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2105","text":"KABUPATEN KEPULAUAN ANAMBAS"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2171","text":"KOTA B A T A M"}');
        Redis::connection('sentinel')->lpush('kota21','{"id":"2172","text":"KOTA TANJUNG PINANG"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3101","text":"KABUPATEN KEPULAUAN SERIBU"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3171","text":"KOTA JAKARTA SELATAN"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3172","text":"KOTA JAKARTA TIMUR"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3173","text":"KOTA JAKARTA PUSAT"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3174","text":"KOTA JAKARTA BARAT"}');
        Redis::connection('sentinel')->lpush('kota31','{"id":"3175","text":"KOTA JAKARTA UTARA"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3201","text":"KABUPATEN BOGOR"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3202","text":"KABUPATEN SUKABUMI"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3203","text":"KABUPATEN CIANJUR"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3204","text":"KABUPATEN BANDUNG"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3205","text":"KABUPATEN GARUT"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3206","text":"KABUPATEN TASIKMALAYA"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3207","text":"KABUPATEN CIAMIS"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3208","text":"KABUPATEN KUNINGAN"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3209","text":"KABUPATEN CIREBON"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3210","text":"KABUPATEN MAJALENGKA"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3211","text":"KABUPATEN SUMEDANG"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3212","text":"KABUPATEN INDRAMAYU"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3213","text":"KABUPATEN SUBANG"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3214","text":"KABUPATEN PURWAKARTA"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3215","text":"KABUPATEN KARAWANG"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3216","text":"KABUPATEN BEKASI"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3217","text":"KABUPATEN BANDUNG BARAT"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3218","text":"KABUPATEN PANGANDARAN"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3271","text":"KOTA BOGOR"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3272","text":"KOTA SUKABUMI"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3273","text":"KOTA BANDUNG"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3274","text":"KOTA CIREBON"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3275","text":"KOTA BEKASI"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3276","text":"KOTA DEPOK"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3277","text":"KOTA CIMAHI"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3278","text":"KOTA TASIKMALAYA"}');
        Redis::connection('sentinel')->lpush('kota32','{"id":"3279","text":"KOTA BANJAR"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3301","text":"KABUPATEN CILACAP"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3302","text":"KABUPATEN BANYUMAS"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3303","text":"KABUPATEN PURBALINGGA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3304","text":"KABUPATEN BANJARNEGARA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3305","text":"KABUPATEN KEBUMEN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3306","text":"KABUPATEN PURWOREJO"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3307","text":"KABUPATEN WONOSOBO"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3308","text":"KABUPATEN MAGELANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3309","text":"KABUPATEN BOYOLALI"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3310","text":"KABUPATEN KLATEN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3311","text":"KABUPATEN SUKOHARJO"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3312","text":"KABUPATEN WONOGIRI"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3313","text":"KABUPATEN KARANGANYAR"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3314","text":"KABUPATEN SRAGEN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3315","text":"KABUPATEN GROBOGAN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3316","text":"KABUPATEN BLORA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3317","text":"KABUPATEN REMBANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3318","text":"KABUPATEN PATI"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3319","text":"KABUPATEN KUDUS"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3320","text":"KABUPATEN JEPARA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3321","text":"KABUPATEN DEMAK"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3322","text":"KABUPATEN SEMARANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3323","text":"KABUPATEN TEMANGGUNG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3324","text":"KABUPATEN KENDAL"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3325","text":"KABUPATEN BATANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3326","text":"KABUPATEN PEKALONGAN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3327","text":"KABUPATEN PEMALANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3328","text":"KABUPATEN TEGAL"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3329","text":"KABUPATEN BREBES"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3371","text":"KOTA MAGELANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3372","text":"KOTA SURAKARTA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3373","text":"KOTA SALATIGA"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3374","text":"KOTA SEMARANG"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3375","text":"KOTA PEKALONGAN"}');
        Redis::connection('sentinel')->lpush('kota33','{"id":"3376","text":"KOTA TEGAL"}');
        Redis::connection('sentinel')->lpush('kota34','{"id":"3401","text":"KABUPATEN KULON PROGO"}');
        Redis::connection('sentinel')->lpush('kota34','{"id":"3402","text":"KABUPATEN BANTUL"}');
        Redis::connection('sentinel')->lpush('kota34','{"id":"3403","text":"KABUPATEN GUNUNG KIDUL"}');
        Redis::connection('sentinel')->lpush('kota34','{"id":"3404","text":"KABUPATEN SLEMAN"}');
        Redis::connection('sentinel')->lpush('kota34','{"id":"3471","text":"KOTA YOGYAKARTA"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3501","text":"KABUPATEN PACITAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3502","text":"KABUPATEN PONOROGO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3503","text":"KABUPATEN TRENGGALEK"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3504","text":"KABUPATEN TULUNGAGUNG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3505","text":"KABUPATEN BLITAR"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3506","text":"KABUPATEN KEDIRI"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3507","text":"KABUPATEN MALANG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3508","text":"KABUPATEN LUMAJANG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3509","text":"KABUPATEN JEMBER"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3510","text":"KABUPATEN BANYUWANGI"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3511","text":"KABUPATEN BONDOWOSO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3512","text":"KABUPATEN SITUBONDO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3513","text":"KABUPATEN PROBOLINGGO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3514","text":"KABUPATEN PASURUAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3515","text":"KABUPATEN SIDOARJO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3516","text":"KABUPATEN MOJOKERTO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3517","text":"KABUPATEN JOMBANG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3518","text":"KABUPATEN NGANJUK"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3519","text":"KABUPATEN MADIUN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3520","text":"KABUPATEN MAGETAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3521","text":"KABUPATEN NGAWI"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3522","text":"KABUPATEN BOJONEGORO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3523","text":"KABUPATEN TUBAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3524","text":"KABUPATEN LAMONGAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3525","text":"KABUPATEN GRESIK"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3526","text":"KABUPATEN BANGKALAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3527","text":"KABUPATEN SAMPANG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3528","text":"KABUPATEN PAMEKASAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3529","text":"KABUPATEN SUMENEP"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3571","text":"KOTA KEDIRI"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3572","text":"KOTA BLITAR"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3573","text":"KOTA MALANG"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3574","text":"KOTA PROBOLINGGO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3575","text":"KOTA PASURUAN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3576","text":"KOTA MOJOKERTO"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3577","text":"KOTA MADIUN"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3578","text":"KOTA SURABAYA"}');
        Redis::connection('sentinel')->lpush('kota35','{"id":"3579","text":"KOTA BATU"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3601","text":"KABUPATEN PANDEGLANG"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3602","text":"KABUPATEN LEBAK"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3603","text":"KABUPATEN TANGERANG"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3604","text":"KABUPATEN SERANG"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3671","text":"KOTA TANGERANG"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3672","text":"KOTA CILEGON"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3673","text":"KOTA SERANG"}');
        Redis::connection('sentinel')->lpush('kota36','{"id":"3674","text":"KOTA TANGERANG SELATAN"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5101","text":"KABUPATEN JEMBRANA"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5102","text":"KABUPATEN TABANAN"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5103","text":"KABUPATEN BADUNG"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5104","text":"KABUPATEN GIANYAR"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5105","text":"KABUPATEN KLUNGKUNG"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5106","text":"KABUPATEN BANGLI"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5107","text":"KABUPATEN KARANG ASEM"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5108","text":"KABUPATEN BULELENG"}');
        Redis::connection('sentinel')->lpush('kota51','{"id":"5171","text":"KOTA DENPASAR"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5201","text":"KABUPATEN LOMBOK BARAT"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5202","text":"KABUPATEN LOMBOK TENGAH"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5203","text":"KABUPATEN LOMBOK TIMUR"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5204","text":"KABUPATEN SUMBAWA"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5205","text":"KABUPATEN DOMPU"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5206","text":"KABUPATEN BIMA"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5207","text":"KABUPATEN SUMBAWA BARAT"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5208","text":"KABUPATEN LOMBOK UTARA"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5271","text":"KOTA MATARAM"}');
        Redis::connection('sentinel')->lpush('kota52','{"id":"5272","text":"KOTA BIMA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5301","text":"KABUPATEN SUMBA BARAT"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5302","text":"KABUPATEN SUMBA TIMUR"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5303","text":"KABUPATEN KUPANG"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5304","text":"KABUPATEN TIMOR TENGAH SELATAN"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5305","text":"KABUPATEN TIMOR TENGAH UTARA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5306","text":"KABUPATEN BELU"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5307","text":"KABUPATEN ALOR"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5308","text":"KABUPATEN LEMBATA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5309","text":"KABUPATEN FLORES TIMUR"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5310","text":"KABUPATEN SIKKA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5311","text":"KABUPATEN ENDE"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5312","text":"KABUPATEN NGADA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5313","text":"KABUPATEN MANGGARAI"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5314","text":"KABUPATEN ROTE NDAO"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5315","text":"KABUPATEN MANGGARAI BARAT"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5316","text":"KABUPATEN SUMBA TENGAH"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5317","text":"KABUPATEN SUMBA BARAT DAYA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5318","text":"KABUPATEN NAGEKEO"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5319","text":"KABUPATEN MANGGARAI TIMUR"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5320","text":"KABUPATEN SABU RAIJUA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5321","text":"KABUPATEN MALAKA"}');
        Redis::connection('sentinel')->lpush('kota53','{"id":"5371","text":"KOTA KUPANG"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6101","text":"KABUPATEN SAMBAS"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6102","text":"KABUPATEN BENGKAYANG"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6103","text":"KABUPATEN LANDAK"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6104","text":"KABUPATEN MEMPAWAH"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6105","text":"KABUPATEN SANGGAU"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6106","text":"KABUPATEN KETAPANG"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6107","text":"KABUPATEN SINTANG"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6108","text":"KABUPATEN KAPUAS HULU"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6109","text":"KABUPATEN SEKADAU"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6110","text":"KABUPATEN MELAWI"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6111","text":"KABUPATEN KAYONG UTARA"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6112","text":"KABUPATEN KUBU RAYA"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6171","text":"KOTA PONTIANAK"}');
        Redis::connection('sentinel')->lpush('kota61','{"id":"6172","text":"KOTA SINGKAWANG"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6201","text":"KABUPATEN KOTAWARINGIN BARAT"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6202","text":"KABUPATEN KOTAWARINGIN TIMUR"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6203","text":"KABUPATEN KAPUAS"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6204","text":"KABUPATEN BARITO SELATAN"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6205","text":"KABUPATEN BARITO UTARA"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6206","text":"KABUPATEN SUKAMARA"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6207","text":"KABUPATEN LAMANDAU"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6208","text":"KABUPATEN SERUYAN"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6209","text":"KABUPATEN KATINGAN"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6210","text":"KABUPATEN PULANG PISAU"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6211","text":"KABUPATEN GUNUNG MAS"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6212","text":"KABUPATEN BARITO TIMUR"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6213","text":"KABUPATEN MURUNG RAYA"}');
        Redis::connection('sentinel')->lpush('kota62','{"id":"6271","text":"KOTA PALANGKA RAYA"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6301","text":"KABUPATEN TANAH LAUT"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6302","text":"KABUPATEN KOTA BARU"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6303","text":"KABUPATEN BANJAR"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6304","text":"KABUPATEN BARITO KUALA"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6305","text":"KABUPATEN TAPIN"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6306","text":"KABUPATEN HULU SUNGAI SELATAN"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6307","text":"KABUPATEN HULU SUNGAI TENGAH"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6308","text":"KABUPATEN HULU SUNGAI UTARA"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6309","text":"KABUPATEN TABALONG"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6310","text":"KABUPATEN TANAH BUMBU"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6311","text":"KABUPATEN BALANGAN"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6371","text":"KOTA BANJARMASIN"}');
        Redis::connection('sentinel')->lpush('kota63','{"id":"6372","text":"KOTA BANJAR BARU"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6401","text":"KABUPATEN PASER"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6402","text":"KABUPATEN KUTAI BARAT"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6403","text":"KABUPATEN KUTAI KARTANEGARA"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6404","text":"KABUPATEN KUTAI TIMUR"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6405","text":"KABUPATEN BERAU"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6409","text":"KABUPATEN PENAJAM PASER UTARA"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6411","text":"KABUPATEN MAHAKAM HULU"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6471","text":"KOTA BALIKPAPAN"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6472","text":"KOTA SAMARINDA"}');
        Redis::connection('sentinel')->lpush('kota64','{"id":"6474","text":"KOTA BONTANG"}');
        Redis::connection('sentinel')->lpush('kota65','{"id":"6501","text":"KABUPATEN MALINAU"}');
        Redis::connection('sentinel')->lpush('kota65','{"id":"6502","text":"KABUPATEN BULUNGAN"}');
        Redis::connection('sentinel')->lpush('kota65','{"id":"6503","text":"KABUPATEN TANA TIDUNG"}');
        Redis::connection('sentinel')->lpush('kota65','{"id":"6504","text":"KABUPATEN NUNUKAN"}');
        Redis::connection('sentinel')->lpush('kota65','{"id":"6571","text":"KOTA TARAKAN"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7101","text":"KABUPATEN BOLAANG MONGONDOW"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7102","text":"KABUPATEN MINAHASA"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7103","text":"KABUPATEN KEPULAUAN SANGIHE"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7104","text":"KABUPATEN KEPULAUAN TALAUD"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7105","text":"KABUPATEN MINAHASA SELATAN"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7106","text":"KABUPATEN MINAHASA UTARA"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7107","text":"KABUPATEN BOLAANG MONGONDOW UTARA"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7108","text":"KABUPATEN SIAU TAGULANDANG BIARO"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7109","text":"KABUPATEN MINAHASA TENGGARA"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7110","text":"KABUPATEN BOLAANG MONGONDOW SELATAN"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7111","text":"KABUPATEN BOLAANG MONGONDOW TIMUR"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7171","text":"KOTA MANADO"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7172","text":"KOTA BITUNG"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7173","text":"KOTA TOMOHON"}');
        Redis::connection('sentinel')->lpush('kota71','{"id":"7174","text":"KOTA KOTAMOBAGU"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7201","text":"KABUPATEN BANGGAI KEPULAUAN"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7202","text":"KABUPATEN BANGGAI"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7203","text":"KABUPATEN MOROWALI"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7204","text":"KABUPATEN POSO"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7205","text":"KABUPATEN DONGGALA"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7206","text":"KABUPATEN TOLI-TOLI"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7207","text":"KABUPATEN BUOL"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7208","text":"KABUPATEN PARIGI MOUTONG"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7209","text":"KABUPATEN TOJO UNA-UNA"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7210","text":"KABUPATEN SIGI"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7211","text":"KABUPATEN BANGGAI LAUT"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7212","text":"KABUPATEN MOROWALI UTARA"}');
        Redis::connection('sentinel')->lpush('kota72','{"id":"7271","text":"KOTA PALU"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7301","text":"KABUPATEN KEPULAUAN SELAYAR"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7302","text":"KABUPATEN BULUKUMBA"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7303","text":"KABUPATEN BANTAENG"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7304","text":"KABUPATEN JENEPONTO"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7305","text":"KABUPATEN TAKALAR"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7306","text":"KABUPATEN GOWA"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7307","text":"KABUPATEN SINJAI"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7308","text":"KABUPATEN MAROS"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7309","text":"KABUPATEN PANGKAJENE DAN KEPULAUAN"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7310","text":"KABUPATEN BARRU"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7311","text":"KABUPATEN BONE"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7312","text":"KABUPATEN SOPPENG"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7313","text":"KABUPATEN WAJO"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7314","text":"KABUPATEN SIDENRENG RAPPANG"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7315","text":"KABUPATEN PINRANG"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7316","text":"KABUPATEN ENREKANG"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7317","text":"KABUPATEN LUWU"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7318","text":"KABUPATEN TANA TORAJA"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7322","text":"KABUPATEN LUWU UTARA"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7325","text":"KABUPATEN LUWU TIMUR"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7326","text":"KABUPATEN TORAJA UTARA"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7371","text":"KOTA MAKASSAR"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7372","text":"KOTA PAREPARE"}');
        Redis::connection('sentinel')->lpush('kota73','{"id":"7373","text":"KOTA PALOPO"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7401","text":"KABUPATEN BUTON"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7402","text":"KABUPATEN MUNA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7403","text":"KABUPATEN KONAWE"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7404","text":"KABUPATEN KOLAKA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7405","text":"KABUPATEN KONAWE SELATAN"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7406","text":"KABUPATEN BOMBANA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7407","text":"KABUPATEN WAKATOBI"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7408","text":"KABUPATEN KOLAKA UTARA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7409","text":"KABUPATEN BUTON UTARA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7410","text":"KABUPATEN KONAWE UTARA"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7411","text":"KABUPATEN KOLAKA TIMUR"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7412","text":"KABUPATEN KONAWE KEPULAUAN"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7413","text":"KABUPATEN MUNA BARAT"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7414","text":"KABUPATEN BUTON TENGAH"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7415","text":"KABUPATEN BUTON SELATAN"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7471","text":"KOTA KENDARI"}');
        Redis::connection('sentinel')->lpush('kota74','{"id":"7472","text":"KOTA BAUBAU"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7501","text":"KABUPATEN BOALEMO"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7502","text":"KABUPATEN GORONTALO"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7503","text":"KABUPATEN POHUWATO"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7504","text":"KABUPATEN BONE BOLANGO"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7505","text":"KABUPATEN GORONTALO UTARA"}');
        Redis::connection('sentinel')->lpush('kota75','{"id":"7571","text":"KOTA GORONTALO"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7601","text":"KABUPATEN MAJENE"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7602","text":"KABUPATEN POLEWALI MANDAR"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7603","text":"KABUPATEN MAMASA"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7604","text":"KABUPATEN MAMUJU"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7605","text":"KABUPATEN MAMUJU UTARA"}');
        Redis::connection('sentinel')->lpush('kota76','{"id":"7606","text":"KABUPATEN MAMUJU TENGAH"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8101","text":"KABUPATEN MALUKU TENGGARA BARAT"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8102","text":"KABUPATEN MALUKU TENGGARA"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8103","text":"KABUPATEN MALUKU TENGAH"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8104","text":"KABUPATEN BURU"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8105","text":"KABUPATEN KEPULAUAN ARU"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8106","text":"KABUPATEN SERAM BAGIAN BARAT"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8107","text":"KABUPATEN SERAM BAGIAN TIMUR"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8108","text":"KABUPATEN MALUKU BARAT DAYA"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8109","text":"KABUPATEN BURU SELATAN"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8171","text":"KOTA AMBON"}');
        Redis::connection('sentinel')->lpush('kota81','{"id":"8172","text":"KOTA TUAL"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8201","text":"KABUPATEN HALMAHERA BARAT"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8202","text":"KABUPATEN HALMAHERA TENGAH"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8203","text":"KABUPATEN KEPULAUAN SULA"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8204","text":"KABUPATEN HALMAHERA SELATAN"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8205","text":"KABUPATEN HALMAHERA UTARA"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8206","text":"KABUPATEN HALMAHERA TIMUR"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8207","text":"KABUPATEN PULAU MOROTAI"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8208","text":"KABUPATEN PULAU TALIABU"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8271","text":"KOTA TERNATE"}');
        Redis::connection('sentinel')->lpush('kota82','{"id":"8272","text":"KOTA TIDORE KEPULAUAN"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9101","text":"KABUPATEN FAKFAK"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9102","text":"KABUPATEN KAIMANA"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9103","text":"KABUPATEN TELUK WONDAMA"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9104","text":"KABUPATEN TELUK BINTUNI"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9105","text":"KABUPATEN MANOKWARI"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9106","text":"KABUPATEN SORONG SELATAN"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9107","text":"KABUPATEN SORONG"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9108","text":"KABUPATEN RAJA AMPAT"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9109","text":"KABUPATEN TAMBRAUW"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9110","text":"KABUPATEN MAYBRAT"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9111","text":"KABUPATEN MANOKWARI SELATAN"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9112","text":"KABUPATEN PEGUNUNGAN ARFAK"}');
        Redis::connection('sentinel')->lpush('kota91','{"id":"9171","text":"KOTA SORONG"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9401","text":"KABUPATEN MERAUKE"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9402","text":"KABUPATEN JAYAWIJAYA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9403","text":"KABUPATEN JAYAPURA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9404","text":"KABUPATEN NABIRE"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9408","text":"KABUPATEN KEPULAUAN YAPEN"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9409","text":"KABUPATEN BIAK NUMFOR"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9410","text":"KABUPATEN PANIAI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9411","text":"KABUPATEN PUNCAK JAYA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9412","text":"KABUPATEN MIMIKA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9413","text":"KABUPATEN BOVEN DIGOEL"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9414","text":"KABUPATEN MAPPI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9415","text":"KABUPATEN ASMAT"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9416","text":"KABUPATEN YAHUKIMO"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9417","text":"KABUPATEN PEGUNUNGAN BINTANG"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9418","text":"KABUPATEN TOLIKARA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9419","text":"KABUPATEN SARMI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9420","text":"KABUPATEN KEEROM"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9426","text":"KABUPATEN WAROPEN"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9427","text":"KABUPATEN SUPIORI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9428","text":"KABUPATEN MAMBERAMO RAYA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9429","text":"KABUPATEN NDUGA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9430","text":"KABUPATEN LANNY JAYA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9431","text":"KABUPATEN MAMBERAMO TENGAH"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9432","text":"KABUPATEN YALIMO"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9433","text":"KABUPATEN PUNCAK"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9434","text":"KABUPATEN DOGIYAI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9435","text":"KABUPATEN INTAN JAYA"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9436","text":"KABUPATEN DEIYAI"}');
        Redis::connection('sentinel')->lpush('kota94','{"id":"9471","text":"KOTA JAYAPURA"}');
        
    }
}
